spring:
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      username: ${mongo.username}
      password: ${mongo.password}
      host: ${mongo.host}
      port: ${mongo.port}
      database: ${mongo.database}
server:
  port: 8089